"""Cloud-embedding RAG for reducing large uploaded context before LLM calls.

No local ML models are loaded here. Embeddings are generated by OpenRouter via
LiteLLM (default: `openrouter/openai/text-embedding-3-small`) and searched
locally with FAISS, which keeps Render-sized instances away from PyTorch.
"""

from __future__ import annotations

import logging
from collections.abc import Iterable, Iterator

from app.config import Settings, get_settings
from app.context_utils import truncate_for_prompt

logger = logging.getLogger(__name__)


def relevant_context_for_prompt(
    *,
    query: str,
    context: str | None,
    settings: Settings | None = None,
) -> str | None:
    """Return the most relevant context chunks for a query.

    Uses cloud embeddings + FAISS when backend dependencies/API keys are available.
    Falls back to existing safe truncation if anything is unavailable.
    """

    settings = settings or get_settings()
    if not context or not context.strip():
        return context

    context = context.strip()
    if not settings.enable_context_rag or len(context) < settings.rag_min_context_chars:
        return truncate_for_prompt(context, settings.max_context_chars)

    try:
        chunks = list(_iter_context_chunks(context, settings))
        if len(chunks) <= settings.rag_top_k:
            return truncate_for_prompt(context, settings.max_context_chars)
        selected = _select_with_cloud_embeddings(query, chunks, settings)
    except Exception as exc:
        logger.warning("RAG unavailable; using truncated context: %s", exc)
        return truncate_for_prompt(context, settings.max_context_chars)

    if not selected:
        return truncate_for_prompt(context, settings.max_context_chars)

    body = "\n\n".join(
        f"### Релевантный фрагмент {index + 1}\n{chunk}"
        for index, chunk in enumerate(selected)
    )
    rag_context = (
        "[Контекст сокращён RAG: эмбеддинги созданы через облачный API, "
        "выбраны наиболее релевантные фрагменты по теме пользователя.]\n\n"
        f"{body}"
    )
    return truncate_for_prompt(rag_context, settings.max_context_chars)


def _iter_context_chunks(context: str, settings: Settings) -> Iterator[str]:
    try:
        from langchain_text_splitters import RecursiveCharacterTextSplitter
    except ImportError:
        yield from _simple_split(context, settings.rag_chunk_size, settings.rag_chunk_overlap)
        return

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=settings.rag_chunk_size,
        chunk_overlap=settings.rag_chunk_overlap,
        separators=["\n\n## ", "\n\n", "\n", ". ", " ", ""],
    )
    for chunk in splitter.split_text(context):
        chunk = chunk.strip()
        if chunk:
            yield chunk


def _simple_split(text: str, chunk_size: int, overlap: int) -> Iterator[str]:
    step = max(1, chunk_size - overlap)
    for start in range(0, len(text), step):
        chunk = text[start : start + chunk_size].strip()
        if chunk:
            yield chunk


def _batched(items: list[str], batch_size: int) -> Iterator[list[str]]:
    batch_size = max(1, batch_size)
    for start in range(0, len(items), batch_size):
        yield items[start : start + batch_size]


def _cloud_embed_texts(texts: list[str], settings: Settings) -> list[list[float]]:
    """Generate embeddings via external API without local ML dependencies."""

    if not texts:
        return []

    try:
        from litellm import embedding
    except ImportError as exc:
        raise RuntimeError("litellm is required for cloud embeddings") from exc

    response = embedding(
        model=settings.rag_embedding_model,
        input=texts,
        api_key=settings.openrouter_api_key.strip() or None,
    )
    data = response.get("data") if isinstance(response, dict) else getattr(response, "data", None)
    if not data:
        raise RuntimeError("embedding API returned no data")

    vectors: list[list[float]] = []
    for item in data:
        vector = item.get("embedding") if isinstance(item, dict) else getattr(item, "embedding", None)
        if vector is None:
            raise RuntimeError("embedding API response item has no embedding")
        vectors.append(list(vector))
    return vectors


def _select_with_cloud_embeddings(query: str, chunks: list[str], settings: Settings) -> list[str]:
    import faiss
    import numpy as np

    query_vectors = _cloud_embed_texts([query], settings)
    query_embedding = _normalize(np.asarray(query_vectors, dtype="float32"))
    if query_embedding.ndim != 2 or query_embedding.shape[0] != 1:
        raise RuntimeError("invalid query embedding shape")

    dimension = query_embedding.shape[1]
    index = faiss.IndexFlatIP(dimension)

    # Build the FAISS index incrementally by embedding context chunks in batches.
    # This avoids keeping a huge embedding matrix in Python memory.
    for batch in _batched(chunks, settings.rag_embedding_batch_size):
        batch_vectors = _cloud_embed_texts(batch, settings)
        batch_embeddings = _normalize(np.asarray(batch_vectors, dtype="float32"))
        if batch_embeddings.ndim != 2 or batch_embeddings.shape[1] != dimension:
            raise RuntimeError("embedding dimension mismatch")
        index.add(batch_embeddings)

    if index.ntotal == 0:
        return []
    top_k = min(settings.rag_top_k, len(chunks))
    _scores, indices = index.search(query_embedding, top_k)
    selected_indices = sorted(int(item) for item in indices[0] if item >= 0)
    return [chunks[index] for index in selected_indices]


def _normalize(vectors):
    import numpy as np

    norms = np.linalg.norm(vectors, axis=1, keepdims=True)
    norms[norms == 0] = 1
    return vectors / norms


def select_relevant_from_chunk_iter(
    *,
    query: str,
    chunks: Iterable[str],
    settings: Settings | None = None,
) -> list[str]:
    """Index a stream of text chunks with cloud embeddings and return top matches.

    This helper is intended for large parsers (for example page-by-page PDF
    extraction) so they can feed chunks into FAISS without loading local ML models.
    """

    settings = settings or get_settings()
    chunk_list = [chunk.strip() for chunk in chunks if chunk and chunk.strip()]
    if not chunk_list:
        return []
    if len(chunk_list) <= settings.rag_top_k:
        return chunk_list
    return _select_with_cloud_embeddings(query, chunk_list, settings)
